baseURL = "http://example.org/"
languageCode = "en-us"
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4
[[menu.main]]
name = "Services"
url = "/services"
weight = 3
[[menu.main]]
name = "About"
url = "/about"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
